---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Amazon EKS Control Plane'

Parameters:
  ClusterName:
    Description: The cluster name provided when the cluster was created.  If it is incorrect, nodes will not be able to join the cluster.
    Type: String
    Default: "TestPOC"

  ClusterVersion:
    Description: Cluster Version
    Type: String
    Default: "latest"
    AllowedValues:
      - "1.10"
      - "1.11"
      - "1.12"
      - "1.13"
      - "latest"

  VpcId:
    Description: The VPC of the worker instances
    Type: AWS::SSM::Parameter::Value<String>
    Default: '/pcpt/VpcId'

  SubnetIds:
    Description: Select 3 subnets where workers can be created.
    Type: List<AWS::EC2::Subnet::Id>
    Default: 'subnet-08f62a40bd41b01b2,subnet-0770cb296c494a60a,subnet-097772746df14bf59,subnet-0216ead0aa4a288be,subnet-03e6a2026dbc1d8c1,subnet-032afbcf5f6faa81c'

Conditions:
  CreateLatestVersionCluster: !Equals [ !Ref ClusterVersion, latest ]
  CreateCustomVersionCluster: !Not [!Equals [!Ref ClusterVersion, latest]]

Resources:
  EKSCluster:
    Type: "AWS::EKS::Cluster"
    Properties:
      Name: !Ref ClusterName
      ResourcesVpcConfig:
        SecurityGroupIds:
          - !Ref ControlPlaneSecurityGroup
        SubnetIds: !Ref SubnetIds
      RoleArn: !GetAtt EksServiceRole.Arn
      Version:
        Fn::If:
          - CreateCustomVersionCluster
          - !Ref ClusterVersion
          - 1.13



  SSMControlPlaneSecurityGroup:
    Type: AWS::SSM::Parameter
    Properties:
      Name: '/pcpt/TestPOC/ControlPlaneSecurityGroup'
      Type: String
      Value: !Ref ControlPlaneSecurityGroup

  ControlPlaneSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Cluster communication with worker nodes
      VpcId: !Ref VpcId

  EksServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "eks.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
      RoleName: !Sub "EksSvcRole-${AWS::StackName}"

Outputs:
  VpcId:
    Value: !Ref VpcId
  SecurityGroups:
    Description: Security group for the cluster control plane communication with worker nodes
    Value: !Join [ ",", [ !Ref ControlPlaneSecurityGroup ] ]
